app:
  host: "0.0.0.0"
  port: 8000

infra:
  redis_url: "redis://redis:6379/0"
  database_url: "postgresql+psycopg2://kommo:kommo@db:5432/kommo"

crm:
  provider: "kommo"
  kommo:
    base_url: "https://YOUR-SUBDOMAIN.kommo.com"
    access_token: "PASTE_TOKEN"

mail:
  smtp_host: "smtp.yourhost.com"
  smtp_port: 465
  smtp_user: "mailer@yourhost.com"
  smtp_pass: "secret"
  from_name: "Noders Outreach"
  from_email: "mailer@yourhost.com"

channels:
  discord:
    bot_token: "xxx"
  telegram:
    bot_token: "xxx"
