clear_logs: true
...

images:
  postgres: "postgres:17.6"
  redis: "redis:8.2-alpine"

runtime:
  python_version: "3.13.7"
  python_debian: "slim-bookworm"

app:
  host: "0.0.0.0"
  port: 8000
...

infra:
  redis_url: "redis://redis:6379/0"
  database_url: "postgresql+psycopg2://kommo:kommo@db:5432/kommo"

crm:
  provider: "kommo"
  kommo:
    base_url: "https://officenodersteam.kommo.com/"
    access_token: "PASTE_TOKEN"       # секрет редактируется
    secret_key: "Nr7KQdR7WORUyw8ShYHvstH8FGCAHKJDhIfZU6zQiQLsDb9ycY7tLKLxOpRztuxA"
    integration_id: "984f9863-f55c-475b-a3aa-18afd34bbde2"
    stages_map: "config/stages.map.json"
    # Произвольные поля и режимы — тянем как есть, если юзер их добавил в settings.yml.
    fields: {address: 195002, discord: 1113985, docs: 1113191, email: null, fund: 1113987, github: 1114007,
  linkedin: 1113201, medium: 1113983, phone: null, reddit: 1113195, telegram: 1113197,
  web: 195000, x: 1113199, youtube: 1113193}
    safe_mode:
      dry_run: true
...
      no_overwrite: true
...

modes:
  research_and_intake:
    enabled: false
...
    tag_create: [bot, new]
  enrich_existing:
    enabled: true
...
    tag_process: [new]

link_collections: [linktr.ee, link3.to, bento.me, hub.xyz]

mail:
  smtp_host: "smtp.yourhost.com"
  smtp_port: 465
...
  smtp_user: "mailer@yourhost.com"
  smtp_pass: "secret"                 # секрет редактируется
  from_name: "Noders Outreach"
  from_email: "mailer@yourhost.com"

channels:
  discord:
    webhook_fallback: ""
  telegram:
    bot_token: "xxx"                  # секрет редактируется

outreach:
  order: [email, discord, form, telegram]
  quiet_hours:
    start: "21:00"
    end: "08:00"
    timezone: "Europe/Moscow"
